language: node_js
node_js:
- stable
install:
- npm install
cache:
  directories:
  - node_modules
notifications:
  email: true
  slack:
    rooms:
      secure: z08qgAg6YXPI3v+VS1Gq2sh+JwjxRZbD9ZRH6Fc2CGOMjeMIXVeqV1N+GTbFOnDxAxHEtSRa9e4RI8h5QFo+aBF2gOFoL7yEKG5UwXSooDpAGkeCGTMOoP9WI+4N+uQawR/A2N2PhCHWFD20a70U3uxeFGlt2X7B9Mf54YAGQJp7g3nTQMw0l9VJGhwenceNuKWv4rQGXg1DamQjW+33iUx4SQnzYJcwlvcwWxNyKR92n06wzDLWhGiaWhfU7rJMN8NfGf84rmRCOyS0q/2CL4xMg/Z1ViFsFpKdb/Fi5QNLnkf41GLy1GuWbjiLYSerrqYiz/LIb3ocOXKdSfSRdAu9bKugl1OVC9bimnFV865otrAGg0WqWq6q+xDaRzSb9sKniRmGad+Y3JPz6VQVLrEq75MKZt6kYo4guAq1Q9dS93Njfr2Vd1z5vkupr9IwyoUgnK6WyIdHx0WeKjTi4i4JbLtDh3YqXZbSfbFjSrIimXSBKVE6azK5Sxb/PkcYGvMYUpoJp6xhLR1bSXlrzRTn9ERF/zte2Ul1zcMczyriGXma4T4YnC7jZsQG8zl18pswRfFIL6PysRnUOObFydGt1syFUDbzCSlQTkrPs9w2dyGEl4kn5sKao0VrVKGdwpOou+fgA1D+wCxAON2qJlEFSucKp3QqOBTtHZpDaLU=
    on_success: always
    on_failure: always
    template:
    - '**%{repository_slug}**, branch: `%{branch}`'
    - 'Build: <%{build_url}|#%{build_number}>), commit: (%{commit})'
    - 'Status: `%{result}` after *%{duration}*'
    - 'Author: _%{author}_'
