language: node_js
node_js:
- stable
install:
- npm install
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: xjvoniGWaZaBcX8awjx6VapW9HiyClzkRs4F6rmJd53GI64BKeSI699zTEMvFn4UFSXDeRgc4dtu4guLP+3M6+P8nbbxZVXO+dTlOcvQyscFdR1Li3zPsi11pHpQC9NzSKnHarTIB1Z5TB264XSL1IF99IppiRlQwGClooRUESfzWdDPEtgOC9CYcuZdQyJk20+H1TENaGrbmaa20o09zO70C1RueeaIp9ZrNJEKcxTMAGVLNXRQe3FeKYQhm1pLWrvI/eRgpfeID3AtklJVOVEOdBi8TCEOZyDgdrvGSm9l7wlAbqxsXRWyksfgHqCMgxTOo1k7aQqep2aveOK+EqvxkS63sGLUb5RvMVfYtX8oTTr9MY9KT2M4I1qli0A6ad30BMlX1xftl2myV8yXELeZieoA2IKnSmkCNtqcJHYWTsqA81UWmwxwZ4IAq8sajjVOhU0heTVcokYZndjSP1ez1zfm3dEU/wVZlO9EEq0vC4siqpxaxn3NOiHikj4rkfFWH2b4sZxAWUCcVhGBboGr6XfQSYWHqg4kWNAEjEglQBRroCgJyUraUtL6LcsFomGmzqhvqe8Q70BJlWxE+f1lnUpJQ5kWWr49bRIbQ/alBUfeA+JlHVCYumaDeiYtvZpFvgtr0FSH/tFWnXAlMqgwEa3YPQ7Hc5+9l+F3oG8=
    template:
      - "**%{repository_slug}, branch: `%{branch}`"
      - "Build <%{build_url}|#%{build_number}>), commit: (%{commit})"
      - "Status: `%{result}` after *%{duration}*"
      - "Author: _%{author}_"