language: node_js
node_js:
- stable
install:
- npm install
cache:
  directories:
  - node_modules
notifications:
  email: true
  slack:
    rooms:
      secure: wtTdt6RwTUv5woNPlcovoHSJzmusj5o+Az1Sl6bEZVJnM9paD+Pc7Hk4yHPFNMoG0NJkugAYECP5FWs1Mi5TluxKK6dV14GW3IGSdZMd+jpdlZZFEuLPdwUGNARPLLCn4Fo3j+aQAooOcm0aK15FkA3vHmv7zX7saQncwGBqw3m683lAhu9Q7SXK/8s0mYOlgv6wwAQteCjhnKPYd6z6D+4mqpT62+y6qKdi1BMp4maoMKbAkNmDzIOonJcbuvATz9SCuQGi2QW09Ma3ebsw4ieOiVqsvdcaedA+omRZNt6y+oQFvBfWzGE2IzAH69vM8Cz8c878LI579AfI33kBbODGlE9xe7bk6xZ33NJ7lMAhM6VKiZJ5jqS2GJV0uI6ulhtQb4sQ+9ds5gWwk2IJpauV8FNX65rz/TUKfnrtCGxWIj2bWv4FB8dRrTFtwV9BBntuJuHwvFYhh5DGU/E1uGe3tMG5KtJ23/Gav+ayTH0CI5Xf8Yv5B59P9JGpm+mDJ2SAXhALsx7H5SDqHzWYxcZntLwdrygIASHhakOuAQaVke/L/YfXjfTfR71SES5a1dzGQwWkn8zq6YzbedyJjllRKyonxcPsrqQ34wKjJti/Og4v1Dajgv1FC9WY3ACtnnt8PTegdT5TnjvRrOLBX/ppNIWAMVsFoDzoC9PvMP0=
    template:
    - '**Build** <%{build_url}|#%{build_number}>, (%{commit})'
    - "**%{repository_slug}@%{branch}**"
    - '`%{result}` after *%{duration}*'
    - 'by _%{author}_'

# Build #15 (f3d1f0c) of bandantonio/tomaatti-timer@integrate-ci-platform by Antonio passed in 0 min 36 sec

# To make Slack notifications work:
# travis login --pro
# travis encrypt --pro "account:token" --add notifications.slack
# Article: https://docs.travis-ci.com/user/encryption-keys/#usage