language: node_js
node_js:
- stable
install:
- npm install
cache:
  directories:
  - node_modules
notifications:
  email: true
  slack:
    slack: mister-gold:y2ZGpIjtTvyQZn80UrgqMiSy#tomaatti-timer
    on_success: always
    on_failure: always
    template:
      - "**%{repository_slug}**, branch: `%{branch}`"
      - "Build: <%{build_url}|#%{build_number}>), commit: (%{commit})"
      - "Status: `%{result}` after *%{duration}*"
      - "Author: _%{author}_"